apiVersion: "core.sns.io/v1"
kind: SNSCluster
metadata:
  name: dev.default.manual.http.myapp
  namespace: sns
  labels:
    domain: http.myapp
    cluster: dev.default.manual
spec:
  kind: manual
  labels:
    X-Zone: "dev"
    X-Lane: "default"
    X-Kind: "manual"
  endpoints:
  - addr: "127.0.0.1:8000"
    state: "enabled"
    weight: 100
    tags:
      Hostname: "hostname1.gz01"
  - addr: "127.0.0.2:8000"
    state: "enabled"
    weight: 100
    tags:
      Hostname: "hostname2.gz01"
