apiVersion: "core.sns.io/v1"
kind: SNSCluster
metadata:
  name: k8s.thrift.api
  namespace: sns
  labels:
    domain: thrift.api
    cluster: k8s
spec:
  tags:
    Environment: "product"
  endpoints:
  - addr: "127.0.0.1:8000"
    state: "enabled"
    weight: 100
    tags:
      Hostname: "hostname1.gz01"
  - addr: "127.0.0.2:8000"
    state: "enabled"
    weight: 100
    tags:
      Hostname: "hostname2.gz01"
