apiVersion: "core.sns.io/v1"
kind: SNSCluster
metadata:
  name: az00.default.manual.thrift.api
  namespace: sns
  labels:
    domain: thrift.api
    cluster: az00.default.manual
spec:
  kind: manual
  labels:
    X-Zone: "az00"
    X-Lane: "default"
    X-Kind: "manual"
  endpoints:
  - addr: "127.0.0.1:8000"
    state: "enabled"
    weight: 100
    tags:
      Hostname: "hostname1.gz01"
  - addr: "127.0.0.2:8000"
    state: "enabled"
    weight: 100
    tags:
      Hostname: "hostname2.gz01"
