apiVersion: apps/v1
kind: Deployment
metadata:
  name: zone00-myapp-deployment
  labels:
    app: zone00-myapp-deployment-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zone00.myapp
  template:
    metadata:
      labels:
        app: zone00.myapp
    spec:
      containers:
      - name: nginx
        image: nginx:1.22
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
