apiVersion: "core.sns.io/v1"
kind: SNSRoutePolicy
metadata:
  name: http.myapp
  namespace: sns
spec:
  routeScript:
    enable: true
    content: |
      -- http.myapp
      if MatchFuncs == nil then
        MatchFuncs = {}
      end
      
      MatchFuncs["http.myapp"] = function(ctx, clusters)
        UserDefineLablesMatch = function(ctx, labels)
          if ctx["X-Zone"] ~= labels["X-Zone"] then
            return false
          end
          if ctx["X-Lane"] ~= labels["X-Lane"] then
            return false
          end
          return true
        end

        DefaultLabelsMatch = function(ctx, labels)
          if ctx["X-Zone"] ~= labels["X-Zone"] then
            return false
          end
          if labels["X-Lane"] ~= "default" then
            return false
          end
          return true
        end
      
        for _, cluster in pairs(clusters) do
          if UserDefineLablesMatch(ctx, cluster.Labels) then
            return { {cluster.Name, 1} }
          end
        end
      
        for _, cluster in pairs(clusters) do
          if DefaultLabelsMatch(ctx, cluster.Labels) then
            return { {cluster.Name, 1} }
          end
        end
      
        return {}
      end
