apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sns-agent
  namespace: kube-system
  labels:
    sns-app: sns-agent
spec:
  selector:
    matchLabels:
      sns-app: sns-agent
  template:
    metadata:
      labels:
        sns-app: sns-agent
    spec:
      hostNetwork: true
      containers:
      - name: sns-agent
        image: docker-registry:5000/sns/agent:latest
        volumeMounts:
        - name: supername-path
          mountPath: /var/supername
        ports:
          - containerPort: 1789
            hostPort: 1789
      volumes:
        - name: supername-path
          hostPath:
            path: /var/supername
