apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-callee-deployment
  labels:
    app: k8s-callee-deployment-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: callee
  template:
    metadata:
      labels:
        app: callee
    spec:
      volumes:
        - name: supername-path
          hostPath:
            path: /var/supername
      containers:
      - name: callee
        image: docker-registry:5000/sns/examples/callee:latest
        volumeMounts:
        - name: supername-path
          mountPath: /var/supername
          readOnly: true
        ports:
        - name: http
          containerPort: 8001
