apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-caller-deployment
  labels:
    app: k8s-caller-deployment-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caller
      cluster: dev.default.k8s
  template:
    metadata:
      labels:
        app: caller
        cluster: dev.default.k8s
    spec:
      volumes:
        - name: supername-path
          hostPath:
            path: /var/supername
      containers:
      - name: caller
        image: docker-registry:5000/sns/examples/caller:latest
        volumeMounts:
        - name: supername-path
          mountPath: /var/supername
          readOnly: true
        ports:
        - name: http
          containerPort: 8000
