apiVersion: apps/v1
kind: Deployment
metadata:
  name: sns-transformer
  namespace: kube-system
  labels:
    sns-app: sns-transformer
spec:
  replicas: 1
  selector:
    matchLabels:
      sns-app: sns-transformer
  template:
    metadata:
      labels:
        sns-app: sns-transformer
    spec:
      containers:
      - name: transformer
        image: docker-registry:5000/sns/transformer:latest
