apiVersion: apps/v1
kind: Deployment
metadata:
  name: sns-transformer-deployment
  labels:
    app: sns-transformer-deployment-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sns-transformer
  template:
    metadata:
      labels:
        app: sns-transformer
    spec:
      containers:
      - name: transformer
        image: docker-registry:5000/sns/transformer:latest
