/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	coresnsiov1 "github.com/ironzhang/sns/kernel/apis/core.sns.io/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSNSRoutePolicies implements SNSRoutePolicyInterface
type FakeSNSRoutePolicies struct {
	Fake *FakeCoreV1
	ns   string
}

var snsroutepoliciesResource = schema.GroupVersionResource{Group: "core.sns.io", Version: "v1", Resource: "snsroutepolicies"}

var snsroutepoliciesKind = schema.GroupVersionKind{Group: "core.sns.io", Version: "v1", Kind: "SNSRoutePolicy"}

// Get takes name of the sNSRoutePolicy, and returns the corresponding sNSRoutePolicy object, and an error if there is any.
func (c *FakeSNSRoutePolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *coresnsiov1.SNSRoutePolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(snsroutepoliciesResource, c.ns, name), &coresnsiov1.SNSRoutePolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*coresnsiov1.SNSRoutePolicy), err
}

// List takes label and field selectors, and returns the list of SNSRoutePolicies that match those selectors.
func (c *FakeSNSRoutePolicies) List(ctx context.Context, opts v1.ListOptions) (result *coresnsiov1.SNSRoutePolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(snsroutepoliciesResource, snsroutepoliciesKind, c.ns, opts), &coresnsiov1.SNSRoutePolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &coresnsiov1.SNSRoutePolicyList{ListMeta: obj.(*coresnsiov1.SNSRoutePolicyList).ListMeta}
	for _, item := range obj.(*coresnsiov1.SNSRoutePolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested sNSRoutePolicies.
func (c *FakeSNSRoutePolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(snsroutepoliciesResource, c.ns, opts))

}

// Create takes the representation of a sNSRoutePolicy and creates it.  Returns the server's representation of the sNSRoutePolicy, and an error, if there is any.
func (c *FakeSNSRoutePolicies) Create(ctx context.Context, sNSRoutePolicy *coresnsiov1.SNSRoutePolicy, opts v1.CreateOptions) (result *coresnsiov1.SNSRoutePolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(snsroutepoliciesResource, c.ns, sNSRoutePolicy), &coresnsiov1.SNSRoutePolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*coresnsiov1.SNSRoutePolicy), err
}

// Update takes the representation of a sNSRoutePolicy and updates it. Returns the server's representation of the sNSRoutePolicy, and an error, if there is any.
func (c *FakeSNSRoutePolicies) Update(ctx context.Context, sNSRoutePolicy *coresnsiov1.SNSRoutePolicy, opts v1.UpdateOptions) (result *coresnsiov1.SNSRoutePolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(snsroutepoliciesResource, c.ns, sNSRoutePolicy), &coresnsiov1.SNSRoutePolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*coresnsiov1.SNSRoutePolicy), err
}

// Delete takes name of the sNSRoutePolicy and deletes it. Returns an error if one occurs.
func (c *FakeSNSRoutePolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(snsroutepoliciesResource, c.ns, name), &coresnsiov1.SNSRoutePolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSNSRoutePolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(snsroutepoliciesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &coresnsiov1.SNSRoutePolicyList{})
	return err
}

// Patch applies the patch and returns the patched sNSRoutePolicy.
func (c *FakeSNSRoutePolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *coresnsiov1.SNSRoutePolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(snsroutepoliciesResource, c.ns, name, pt, data, subresources...), &coresnsiov1.SNSRoutePolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*coresnsiov1.SNSRoutePolicy), err
}
