/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/ironzhang/sns/kernel/apis/core.sns.io/v1"
	scheme "github.com/ironzhang/sns/kernel/clients/coresnsclients/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SNSRoutePoliciesGetter has a method to return a SNSRoutePolicyInterface.
// A group's client should implement this interface.
type SNSRoutePoliciesGetter interface {
	SNSRoutePolicies(namespace string) SNSRoutePolicyInterface
}

// SNSRoutePolicyInterface has methods to work with SNSRoutePolicy resources.
type SNSRoutePolicyInterface interface {
	Create(ctx context.Context, sNSRoutePolicy *v1.SNSRoutePolicy, opts metav1.CreateOptions) (*v1.SNSRoutePolicy, error)
	Update(ctx context.Context, sNSRoutePolicy *v1.SNSRoutePolicy, opts metav1.UpdateOptions) (*v1.SNSRoutePolicy, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.SNSRoutePolicy, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.SNSRoutePolicyList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.SNSRoutePolicy, err error)
	SNSRoutePolicyExpansion
}

// sNSRoutePolicies implements SNSRoutePolicyInterface
type sNSRoutePolicies struct {
	client rest.Interface
	ns     string
}

// newSNSRoutePolicies returns a SNSRoutePolicies
func newSNSRoutePolicies(c *CoreV1Client, namespace string) *sNSRoutePolicies {
	return &sNSRoutePolicies{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the sNSRoutePolicy, and returns the corresponding sNSRoutePolicy object, and an error if there is any.
func (c *sNSRoutePolicies) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.SNSRoutePolicy, err error) {
	result = &v1.SNSRoutePolicy{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("snsroutepolicies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SNSRoutePolicies that match those selectors.
func (c *sNSRoutePolicies) List(ctx context.Context, opts metav1.ListOptions) (result *v1.SNSRoutePolicyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.SNSRoutePolicyList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("snsroutepolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested sNSRoutePolicies.
func (c *sNSRoutePolicies) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("snsroutepolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a sNSRoutePolicy and creates it.  Returns the server's representation of the sNSRoutePolicy, and an error, if there is any.
func (c *sNSRoutePolicies) Create(ctx context.Context, sNSRoutePolicy *v1.SNSRoutePolicy, opts metav1.CreateOptions) (result *v1.SNSRoutePolicy, err error) {
	result = &v1.SNSRoutePolicy{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("snsroutepolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(sNSRoutePolicy).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a sNSRoutePolicy and updates it. Returns the server's representation of the sNSRoutePolicy, and an error, if there is any.
func (c *sNSRoutePolicies) Update(ctx context.Context, sNSRoutePolicy *v1.SNSRoutePolicy, opts metav1.UpdateOptions) (result *v1.SNSRoutePolicy, err error) {
	result = &v1.SNSRoutePolicy{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("snsroutepolicies").
		Name(sNSRoutePolicy.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(sNSRoutePolicy).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the sNSRoutePolicy and deletes it. Returns an error if one occurs.
func (c *sNSRoutePolicies) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("snsroutepolicies").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *sNSRoutePolicies) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("snsroutepolicies").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched sNSRoutePolicy.
func (c *sNSRoutePolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.SNSRoutePolicy, err error) {
	result = &v1.SNSRoutePolicy{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("snsroutepolicies").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
